apiVersion: v1
kind: Service
metadata: 
  name: backend
  namespace: chat-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001       # Port exposed inside the cluster
      targetPort: 5001 # Matches container port
